DROP TRIGGER IF EXISTS evidence_reference_tenant_guard ON evidence;
DROP FUNCTION IF EXISTS enforce_evidence_reference_tenant();
ALTER TABLE data_quality_event DROP CONSTRAINT IF EXISTS quality_property_tenant_fk;
ALTER TABLE data_quality_event DROP CONSTRAINT IF EXISTS quality_source_tenant_fk;
ALTER TABLE action DROP CONSTRAINT IF EXISTS action_decision_tenant_fk;
ALTER TABLE alert DROP CONSTRAINT IF EXISTS alert_property_tenant_fk;
ALTER TABLE alert DROP CONSTRAINT IF EXISTS alert_decision_tenant_fk;
ALTER TABLE decision DROP CONSTRAINT IF EXISTS decision_property_tenant_fk;
ALTER TABLE evidence DROP CONSTRAINT IF EXISTS evidence_source_tenant_fk;
ALTER TABLE observation DROP CONSTRAINT IF EXISTS observation_property_tenant_fk;
ALTER TABLE observation DROP CONSTRAINT IF EXISTS observation_source_tenant_fk;
ALTER TABLE property DROP CONSTRAINT IF EXISTS property_tenant_id_uq;
ALTER TABLE source DROP CONSTRAINT IF EXISTS source_tenant_id_uq;
ALTER TABLE decision DROP CONSTRAINT IF EXISTS decision_tenant_id_uq;
ALTER TABLE observation ADD CONSTRAINT observation_property_id_fkey FOREIGN KEY (property_id) REFERENCES property(id);
ALTER TABLE observation ADD CONSTRAINT observation_source_id_fkey FOREIGN KEY (source_id) REFERENCES source(id);
ALTER TABLE evidence ADD CONSTRAINT evidence_source_id_fkey FOREIGN KEY (source_id) REFERENCES source(id);
ALTER TABLE decision ADD CONSTRAINT decision_property_id_fkey FOREIGN KEY (property_id) REFERENCES property(id);
ALTER TABLE alert ADD CONSTRAINT alert_property_id_fkey FOREIGN KEY (property_id) REFERENCES property(id);
ALTER TABLE alert ADD CONSTRAINT alert_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES decision(id);
ALTER TABLE action ADD CONSTRAINT action_decision_id_fkey FOREIGN KEY (decision_id) REFERENCES decision(id);
ALTER TABLE data_quality_event ADD CONSTRAINT data_quality_event_property_id_fkey FOREIGN KEY (property_id) REFERENCES property(id);
ALTER TABLE data_quality_event ADD CONSTRAINT data_quality_event_source_id_fkey FOREIGN KEY (source_id) REFERENCES source(id);
