from __future__ import annotations

import hashlib
import os
import tempfile
import time
import urllib.parse
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import StrEnum
from pathlib import Path
from typing import Any, Callable, Protocol

from prometheus_client import Counter, Histogram

from .object_storage import LocalObjectStorage, ObjectStorageError
from .security import NetworkPolicy, SSRFBlocked

try:  # boto3 is an infrastructure dependency; keep import failures explicit.
    import boto3
    from botocore.client import Config as BotoConfig
    from botocore.exceptions import (
        ClientError,
        EndpointConnectionError,
        NoCredentialsError,
        PartialCredentialsError,
        ReadTimeoutError,
    )
except ImportError:  # pragma: no cover - exercised only in broken deployments
    boto3 = None  # type: ignore[assignment]
    BotoConfig = None  # type: ignore[assignment,misc]
    ClientError = EndpointConnectionError = NoCredentialsError = (  # type: ignore[assignment,misc]
        PartialCredentialsError
    ) = ReadTimeoutError = Exception


CDSE_S3_BYTES = Counter(
    "ribeira_cdse_s3_download_bytes_total",
    "Bytes downloaded from the configured CDSE S3 endpoint",
)
CDSE_S3_DOWNLOADS = Counter(
    "ribeira_cdse_s3_download_total", "CDSE S3 asset download attempts", ["status"]
)
CDSE_S3_ERRORS = Counter(
    "ribeira_cdse_s3_download_errors_total", "CDSE S3 asset download errors", ["code"]
)
CDSE_S3_LATENCY = Histogram(
    "ribeira_cdse_s3_download_latency_seconds", "CDSE S3 download duration"
)


class AssetAccessStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    CACHED = "CACHED"
    BLOCKED_BY_CREDENTIAL = "BLOCKED_BY_CREDENTIAL"
    PROVIDER_AUTHENTICATION_FAILED = "PROVIDER_AUTHENTICATION_FAILED"
    ASSET_UNAVAILABLE = "ASSET_UNAVAILABLE"
    ASSET_TOO_LARGE = "ASSET_TOO_LARGE"
    INVALID_ASSET_REFERENCE = "INVALID_ASSET_REFERENCE"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"


@dataclass(frozen=True)
class AssetCredentials:
    access_key: str
    secret_key: str


class CredentialProviderPort(Protocol):
    def get_credentials(self) -> AssetCredentials | None: ...


@dataclass(frozen=True)
class EnvironmentCredentialProvider:
    """Infrastructure-only environment credential source.

    Secret values are never included in this object's representation or in any
    exception generated by the S3 adapter.
    """

    access_key_name: str = "CDSE_S3_ACCESS_KEY"
    secret_key_name: str = "CDSE_S3_SECRET_KEY"

    def get_credentials(self) -> AssetCredentials | None:
        access_key = os.getenv(self.access_key_name)
        secret_key = os.getenv(self.secret_key_name)
        if not access_key or not secret_key:
            return None
        return AssetCredentials(access_key=access_key, secret_key=secret_key)


@dataclass(frozen=True)
class CdseS3Config:
    provider_id: str = "COPERNICUS_CDSE"
    endpoint: str = "https://eodata.dataspace.copernicus.eu"
    bucket: str = "eodata"
    timeout_seconds: float = 60.0
    max_object_bytes: int = 500_000_000
    max_job_bytes: int = 1_000_000_000
    # Quality-masked NDVI requires the two reflectance inputs plus official SCL.
    max_assets_per_job: int = 3
    chunk_bytes: int = 1024 * 1024
    max_retries: int = 2
    documentation_url: str = (
        "https://documentation.dataspace.copernicus.eu/APIs/S3.html"
    )

    @classmethod
    def from_environment(cls) -> "CdseS3Config":
        def integer(name: str, default: int) -> int:
            value = os.getenv(name)
            if value is None or value == "":
                return default
            try:
                parsed = int(value)
            except ValueError as exc:
                raise ValueError(f"{name} must be an integer") from exc
            if parsed <= 0:
                raise ValueError(f"{name} must be positive")
            return parsed

        endpoint = os.getenv("CDSE_S3_ENDPOINT") or cls.endpoint
        bucket = os.getenv("CDSE_S3_BUCKET") or cls.bucket
        return cls(
            endpoint=endpoint,
            bucket=bucket,
            timeout_seconds=float(os.getenv("CDSE_S3_TIMEOUT_SECONDS", "60")),
            max_object_bytes=integer("CDSE_S3_MAX_OBJECT_BYTES", cls.max_object_bytes),
            max_job_bytes=integer("CDSE_S3_MAX_JOB_BYTES", cls.max_job_bytes),
            max_assets_per_job=integer(
                "CDSE_S3_MAX_ASSETS_PER_JOB", cls.max_assets_per_job
            ),
            chunk_bytes=integer("CDSE_S3_CHUNK_BYTES", cls.chunk_bytes),
            max_retries=integer("CDSE_S3_MAX_RETRIES", cls.max_retries),
        )


@dataclass(frozen=True)
class ParsedS3Reference:
    bucket: str
    object_key: str


@dataclass(frozen=True)
class AssetDownloadResult:
    status: AssetAccessStatus
    href: str
    bucket: str | None = None
    object_key: str | None = None
    size_bytes: int | None = None
    bytes_downloaded: int = 0
    checksum_algorithm: str | None = None
    checksum_local: str | None = None
    checksum_provider: str | None = None
    local_reference: str | None = None
    started_at: str | None = None
    finished_at: str | None = None
    failure_code: str | None = None


class AssetAccessError(RuntimeError):
    def __init__(self, status: AssetAccessStatus, code: str, message: str) -> None:
        super().__init__(message)
        self.status = status
        self.code = code


def parse_cdse_s3_reference(href: str, config: CdseS3Config) -> ParsedS3Reference:
    parsed = urllib.parse.urlparse(href)
    if (
        parsed.scheme.lower() != "s3"
        or not parsed.netloc
        or not parsed.path
        or parsed.query
        or parsed.fragment
    ):
        raise AssetAccessError(
            AssetAccessStatus.INVALID_ASSET_REFERENCE,
            "INVALID_SCHEME_OR_PATH",
            "CDSE asset reference must be an s3 URI with an object key",
        )
    bucket = parsed.netloc.lower()
    object_key = parsed.path.lstrip("/")
    if bucket != config.bucket.lower():
        raise AssetAccessError(
            AssetAccessStatus.ASSET_UNAVAILABLE,
            "BUCKET_NOT_ALLOWED",
            "CDSE asset bucket is not allowlisted",
        )
    if not object_key or object_key.startswith("/"):
        raise AssetAccessError(
            AssetAccessStatus.INVALID_ASSET_REFERENCE,
            "EMPTY_OBJECT_KEY",
            "CDSE asset object key is invalid",
        )
    parts = object_key.split("/")
    if any(part in {"", ".", ".."} for part in parts):
        raise AssetAccessError(
            AssetAccessStatus.INVALID_ASSET_REFERENCE,
            "UNSAFE_OBJECT_KEY",
            "CDSE asset object key is invalid",
        )
    return ParsedS3Reference(bucket=bucket, object_key=object_key)


class CdseS3AssetAdapter:
    """Bounded, provider-specific access to CDSE's authenticated S3 API."""

    def __init__(
        self,
        object_storage: LocalObjectStorage,
        credential_provider: CredentialProviderPort | None = None,
        config: CdseS3Config | None = None,
        network_policy: NetworkPolicy | None = None,
        client_factory: Callable[[CdseS3Config, AssetCredentials], Any] | None = None,
    ) -> None:
        self.object_storage = object_storage
        self.credential_provider = (
            credential_provider or EnvironmentCredentialProvider()
        )
        self.config = config or CdseS3Config.from_environment()
        self.client_factory = client_factory
        parsed = urllib.parse.urlparse(self.config.endpoint)
        configured_hosts = {
            "eodata.dataspace.copernicus.eu",
            "eodata.ams.dataspace.copernicus.eu",
        }
        if parsed.scheme != "https" or parsed.hostname not in configured_hosts:
            raise ValueError("CDSE S3 endpoint must be an allowlisted HTTPS endpoint")
        self.network_policy = network_policy or NetworkPolicy(
            allowed_hosts=frozenset(configured_hosts)
        )

    def _validate_endpoint(self) -> None:
        try:
            self.network_policy.validate(self.config.endpoint)
        except SSRFBlocked as exc:
            raise AssetAccessError(
                AssetAccessStatus.SOURCE_UNAVAILABLE,
                "ENDPOINT_BLOCKED",
                "configured CDSE S3 endpoint is blocked by network policy",
            ) from exc

    def _client(self, credentials: AssetCredentials) -> Any:
        if self.client_factory is not None:
            return self.client_factory(self.config, credentials)
        if boto3 is None or BotoConfig is None:
            raise AssetAccessError(
                AssetAccessStatus.SOURCE_UNAVAILABLE,
                "S3_DEPENDENCY_UNAVAILABLE",
                "CDSE S3 client dependency is unavailable",
            )
        self._validate_endpoint()
        return boto3.client(
            "s3",
            endpoint_url=self.config.endpoint,
            aws_access_key_id=credentials.access_key,
            aws_secret_access_key=credentials.secret_key,
            region_name="default",
            verify=True,
            config=BotoConfig(
                signature_version="s3v4",
                s3={"addressing_style": "path"},
                retries={"mode": "standard", "max_attempts": self.config.max_retries},
                connect_timeout=int(self.config.timeout_seconds),
                read_timeout=int(self.config.timeout_seconds),
            ),
        )

    def download(
        self,
        href: str,
        storage_key: str,
        max_job_bytes: int | None = None,
    ) -> AssetDownloadResult:
        try:
            parsed = parse_cdse_s3_reference(href, self.config)
        except AssetAccessError as exc:
            return AssetDownloadResult(
                status=exc.status,
                href=href,
                failure_code=exc.code,
            )
        credentials = self.credential_provider.get_credentials()
        if credentials is None:
            CDSE_S3_DOWNLOADS.labels(
                AssetAccessStatus.BLOCKED_BY_CREDENTIAL.value
            ).inc()
            return AssetDownloadResult(
                status=AssetAccessStatus.BLOCKED_BY_CREDENTIAL,
                href=href,
                bucket=parsed.bucket,
                object_key=parsed.object_key,
                failure_code="MISSING_CREDENTIALS",
            )
        if max_job_bytes is not None and max_job_bytes <= 0:
            raise ValueError("max_job_bytes must be positive")
        started = datetime.now(timezone.utc).isoformat()
        start_clock = time.perf_counter()
        temporary_name: str | None = None
        try:
            client = self._client(credentials)
            head = client.head_object(Bucket=parsed.bucket, Key=parsed.object_key)
            size_value = head.get("ContentLength")
            size = int(size_value) if size_value is not None else None
            if size is not None and size > self.config.max_object_bytes:
                raise AssetAccessError(
                    AssetAccessStatus.ASSET_TOO_LARGE,
                    "OBJECT_SIZE_LIMIT",
                    "CDSE asset exceeds the configured object size limit",
                )
            if size is not None and max_job_bytes is not None and size > max_job_bytes:
                raise AssetAccessError(
                    AssetAccessStatus.ASSET_TOO_LARGE,
                    "JOB_SIZE_LIMIT",
                    "CDSE asset exceeds the configured job size limit",
                )
            provider_checksum = next(
                (
                    str(head[key])
                    for key in ("ChecksumSHA256", "ChecksumSHA1", "ChecksumCRC32C")
                    if head.get(key)
                ),
                None,
            )
            with tempfile.NamedTemporaryFile(
                prefix="ribeira-cdse-", suffix=".asset", delete=False
            ) as temporary:
                temporary_name = temporary.name
                body = client.get_object(Bucket=parsed.bucket, Key=parsed.object_key)[
                    "Body"
                ]
                digest = hashlib.sha256()
                downloaded = 0
                try:
                    while True:
                        chunk = body.read(self.config.chunk_bytes)
                        if not chunk:
                            break
                        downloaded += len(chunk)
                        if downloaded > self.config.max_object_bytes or (
                            max_job_bytes is not None and downloaded > max_job_bytes
                        ):
                            raise AssetAccessError(
                                AssetAccessStatus.ASSET_TOO_LARGE,
                                "STREAM_SIZE_LIMIT",
                                "CDSE asset exceeded the configured download limit",
                            )
                        digest.update(chunk)
                        temporary.write(chunk)
                finally:
                    close = getattr(body, "close", None)
                    if callable(close):
                        close()
            local_reference, checksum, stored_bytes = self.object_storage.put_file(
                storage_key, temporary_name, max_bytes=self.config.max_object_bytes
            )
            result = AssetDownloadResult(
                status=AssetAccessStatus.SUCCEEDED,
                href=href,
                bucket=parsed.bucket,
                object_key=parsed.object_key,
                size_bytes=size if size is not None else stored_bytes,
                bytes_downloaded=stored_bytes,
                checksum_algorithm="SHA-256",
                checksum_local=checksum,
                checksum_provider=provider_checksum,
                local_reference=local_reference,
                started_at=started,
                finished_at=datetime.now(timezone.utc).isoformat(),
            )
            CDSE_S3_DOWNLOADS.labels(AssetAccessStatus.SUCCEEDED.value).inc()
            CDSE_S3_BYTES.inc(stored_bytes)
            return result
        except AssetAccessError as exc:
            CDSE_S3_DOWNLOADS.labels(exc.status.value).inc()
            CDSE_S3_ERRORS.labels(exc.code).inc()
            return AssetDownloadResult(
                status=exc.status,
                href=href,
                bucket=parsed.bucket,
                object_key=parsed.object_key,
                started_at=started,
                finished_at=datetime.now(timezone.utc).isoformat(),
                failure_code=exc.code,
            )
        except (NoCredentialsError, PartialCredentialsError):
            CDSE_S3_DOWNLOADS.labels(
                AssetAccessStatus.PROVIDER_AUTHENTICATION_FAILED.value
            ).inc()
            CDSE_S3_ERRORS.labels("AUTHENTICATION_FAILED").inc()
            return AssetDownloadResult(
                status=AssetAccessStatus.PROVIDER_AUTHENTICATION_FAILED,
                href=href,
                bucket=parsed.bucket,
                object_key=parsed.object_key,
                started_at=started,
                finished_at=datetime.now(timezone.utc).isoformat(),
                failure_code="AUTHENTICATION_FAILED",
            )
        except ClientError as exc:
            code = str(getattr(exc, "response", {}).get("Error", {}).get("Code", ""))
            auth_codes = {
                "AccessDenied",
                "InvalidAccessKeyId",
                "SignatureDoesNotMatch",
                "ExpiredToken",
                "InvalidToken",
            }
            status = (
                AssetAccessStatus.PROVIDER_AUTHENTICATION_FAILED
                if code in auth_codes
                else AssetAccessStatus.ASSET_UNAVAILABLE
            )
            safe_code = (
                "AUTHENTICATION_FAILED"
                if status == AssetAccessStatus.PROVIDER_AUTHENTICATION_FAILED
                else (
                    "OBJECT_UNAVAILABLE"
                    if code in {"NoSuchKey", "404", "NotFound"}
                    else "PROVIDER_ERROR"
                )
            )
            CDSE_S3_DOWNLOADS.labels(status.value).inc()
            CDSE_S3_ERRORS.labels(safe_code).inc()
            return AssetDownloadResult(
                status=status,
                href=href,
                bucket=parsed.bucket,
                object_key=parsed.object_key,
                started_at=started,
                finished_at=datetime.now(timezone.utc).isoformat(),
                failure_code=safe_code,
            )
        except (EndpointConnectionError, ReadTimeoutError, TimeoutError, OSError):
            CDSE_S3_DOWNLOADS.labels(AssetAccessStatus.SOURCE_UNAVAILABLE.value).inc()
            CDSE_S3_ERRORS.labels("SOURCE_UNAVAILABLE").inc()
            return AssetDownloadResult(
                status=AssetAccessStatus.SOURCE_UNAVAILABLE,
                href=href,
                bucket=parsed.bucket,
                object_key=parsed.object_key,
                started_at=started,
                finished_at=datetime.now(timezone.utc).isoformat(),
                failure_code="SOURCE_UNAVAILABLE",
            )
        except ObjectStorageError:
            CDSE_S3_DOWNLOADS.labels(AssetAccessStatus.ASSET_UNAVAILABLE.value).inc()
            CDSE_S3_ERRORS.labels("LOCAL_STORAGE_ERROR").inc()
            return AssetDownloadResult(
                status=AssetAccessStatus.ASSET_UNAVAILABLE,
                href=href,
                bucket=parsed.bucket,
                object_key=parsed.object_key,
                started_at=started,
                finished_at=datetime.now(timezone.utc).isoformat(),
                failure_code="LOCAL_STORAGE_ERROR",
            )
        finally:
            if temporary_name is not None:
                Path(temporary_name).unlink(missing_ok=True)
            CDSE_S3_LATENCY.observe(time.perf_counter() - start_clock)
