from __future__ import annotations

from enum import StrEnum


class DataClassification(StrEnum):
    OBSERVED = "OBSERVED"
    OFFICIAL_SOURCE = "OFFICIAL_SOURCE"
    MANUAL_CONFIRMED = "MANUAL_CONFIRMED"
    CALCULATED = "CALCULATED"
    DERIVED = "DERIVED"
    INFERRED = "INFERRED"
    PREDICTED = "PREDICTED"
    ASSUMPTION = "ASSUMPTION"
    SIMULATED = "SIMULATED"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"


class QualityFlag(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    UNKNOWN = "UNKNOWN"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    CONFLICTING = "CONFLICTING"


class IngestionStatus(StrEnum):
    INGESTED = "INGESTED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    INVALID_PAYLOAD = "INVALID_PAYLOAD"
    PARTIAL = "PARTIAL"


class DecisionStatus(StrEnum):
    ACTIONABLE = "ACTIONABLE"
    INCONCLUSIVE = "INCONCLUSIVE"
    CONFLICTING = "CONFLICTING"
    NO_TRIGGER = "NO_TRIGGER"


class RuleAuthority(StrEnum):
    REGRA_RIBEIRA = "REGRA_RIBEIRA"
    REGRA_CLIENTE = "REGRA_CLIENTE"
    REGRA_REGULATORIA = "REGRA_REGULATORIA"
    REGRA_AGRONOMICA = "REGRA_AGRONOMICA"
    REGRA_TECNICA = "REGRA_TECNICA"
    REGRA_MODELO = "REGRA_MODELO"
